"""
generate_risk_register.py

Reads a CSV of identified AI risks and generates a fully scored, sorted,
formatted risk register as an Excel file.

Usage:
    python generate_risk_register.py input_risks.csv output_register.xlsx

Expected CSV columns:
    risk_id, risk_type, description, likelihood, severity,
    trustworthy_ai_property

BridgeCore AI LLC — AI GRC Engineering
"""

import sys
import pandas as pd
from datetime import datetime
from risk_rating import calculate_risk_rating


def generate_risk_register(input_csv_path, output_path):
    """
    Reads a CSV of identified risks and generates a scored risk register.

    Args:
        input_csv_path (str): Path to the input CSV of identified risks
        output_path (str): Path where the output Excel file will be saved

    Returns:
        tuple: (DataFrame of the scored register, dict of rating counts)
    """
    df = pd.read_csv(input_csv_path)

    required_columns = ['risk_id', 'risk_type', 'description',
                         'likelihood', 'severity']
    missing = [col for col in required_columns if col not in df.columns]
    if missing:
        raise ValueError(f"Input CSV is missing required columns: {missing}")

    # Apply the rating function to every row
    df['composite_rating'] = df.apply(
        lambda row: calculate_risk_rating(row['likelihood'], row['severity']),
        axis=1
    )

    # Sort so Critical and High risks appear first
    rating_order = {'Critical': 0, 'High': 1, 'Medium': 2, 'Low': 3, 'Accept': 4}
    df['sort_order'] = df['composite_rating'].map(rating_order)
    df = df.sort_values('sort_order').drop('sort_order', axis=1)

    # Add metadata
    df['assessment_date'] = datetime.now().strftime('%Y-%m-%d')

    # Generate summary statistics
    summary = df['composite_rating'].value_counts().to_dict()

    print("=" * 50)
    print("AI Risk Register — Generated by BridgeCore AI LLC")
    print("=" * 50)
    print(f"Total risks processed: {len(df)}")
    print(f"Rating summary: {summary}")
    print("=" * 50)

    # Export to Excel
    df.to_excel(output_path, index=False, sheet_name='Risk Register')
    print(f"\nRisk register saved to: {output_path}")

    return df, summary


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python generate_risk_register.py <input.csv> <output.xlsx>")
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    generate_risk_register(input_path, output_path)
